# Site settings
title: Novakov's notes of code
description: Maciej 'Novakov' Nowak and his adventures with code
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://novakov.github.io" # the base hostname & protocol for your site

timezone: Europe/Warsaw

owner:
  name: Maciej Nowak
  email: maciejt.nowak@gmail.com
  twitter: maciejt_nowak
  stackexchange: Novakov
  github: Novakov

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      share: false

gems:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5

menu:
  - title: 'Home'
    url: '/'
  - title: 'GitHub'
    url: 'http://github.com/Novakov'

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

post_layout: post
page_layout: page
